### ISSUE TITLE
Update pkgdown yml file with correct links

### ISSUE THREAD

**Issue by mianzg** [openwashdata/waterpumpkwale#2]

**Comment by larnsce** [comment]
The plausible script does not need the package name anymore. We now track everything through the main github pages domain:

https://github.com/openwashdata/waterpumpkwale/blob/496402f89ba6d2086c10492dd25af8cc7e859731/_pkgdown.yml#L6

```
template:
  bootstrap: 5
  includes:
    in_header: |
      <script defer data-domain="openwashdata.github.io" src="https://plausible.io/js/script.js"></script>
```
